INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'АО "АКОС"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'АО "АПЕКС"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'АО "Воентелеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'АО "ГЛОНАСС"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'АО "ГлобалТел"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'АО "КантриКом"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'АО "Компания ТрансТелеКом"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'АО "Севастополь Телеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'АО "Теле2-Санкт-Петербург"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'АО "ЭР-Телеком Холдинг"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'Акционерное общество "Крымтелеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'Акционерное общество "Тандер"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ЗАО "Вайнах Телеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ЗАО "Джи Ти Эн Ти"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ЗАО "Интерсвязь-2"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ЗАО "СанСим"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ОАО "АСВТ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ОАО "МТТ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ОАО "Сургутнефтегаз"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Аврора Телеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Антарес"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Арктур"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Астран"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "БИТ-ЦЕНТР"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Белитон"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ВТБ Мобайл"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ВиКом"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ГЛОНАСС МОБАЙЛ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Газпром телеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Глобал Телеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ЕКАТЕРИНБУРГ-2000"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Интеграл"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Интернод"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Иридиум Коммьюникешенс"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "К-телеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "КТК ТЕЛЕКОМ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Квантек"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "КватроПлюс"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Лайкамобайл"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Лардекс"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "МАТРИКС телеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "МОСТЕЛЕКОМ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "МСН Телеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Медиа-Маркет"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Метро-пэй"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "МиАТел"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "НЦИ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Новые мобильные коммуникации"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Нэт Бай Нэт Холдинг"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ОБИТ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Оранж Бизнес Сервисез"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ПИН"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Плинтрон"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "РЕКОНН"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "РЕТЕЙЛ ИННОВАЦИИ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "СВЯЗЬРЕСУРС-МОБАЙЛ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "СИМ ТЕЛЕКОМ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "СИНТОНИК"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Сбербанк-Телеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "СевТелекомСвязь"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Скай Нетворкс"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "СкайНэт"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Скартел"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Сонет"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Спринт"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Старт"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Т2 Мобайл"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ТВЕ-ТЕЛЕКОМ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ТМТ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ТРАСТЕЛ"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ТРН-телеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ТТК-Связь"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Тинькофф Мобайл"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Тривон Нетворкс"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Центр 2М"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Цифра Один"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Цифра групп"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ЭКО Нетворкс"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Элемтэ-Инвест"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "Юнисел"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ООО "ЮнитТелеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ПАО "Вымпел-Коммуникации"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ПАО "МГТС"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ПАО "МегаФон"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ПАО "Мобильные ТелеСистемы"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ПАО "Ростелеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ПАО "Таттелеком"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (0, NULL, 'ФГУП "Морсвязьспутник"', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Амурская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Архангельская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Астраханская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Белгородская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Брянская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Владимирская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Волгоградская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Вологодская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Воронежская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Еврейская АО', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Ивановская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Иркутская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Калининградская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Калужская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Камчатский край', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Кемеровская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Костромская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Краснодарский край', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Красноярский край', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Курганская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Курская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Ленинградская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Липецкая обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Магаданская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Московская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Мурманская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Нижегородская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Новгородская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Новосибирская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Омская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Оренбургская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Орловская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Пензенская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Пермский край', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Приморский край', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Псковская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Башкортостан', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Бурятия', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Дагестан', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Ингушетия', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Кабардино-Балкария', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Калмыкия', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Карачаево-Черкессия', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Карелия', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Коми', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Марий-Эл', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Мордовия', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Саха - Якутия', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Северная Осетия - Алания', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Татарстан', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Тыва', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Удмуртия', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Хакассия', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Респ. Чувашия', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Республика Адыгея', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Республика Алтай', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Ростовская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Рязанская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Самарская обл', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Саратовская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Сахалинская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Свердловская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Смоленская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Ставропольский край', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Таймыр', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Тамбовская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Тверская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Томская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Тульская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Тюменская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Ульяновская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Хабаровский край', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Ханты-Мансийский АО', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Челябинская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Чеченская Респ.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Читинская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'Ярославская обл.', NULL);
INSERT INTO TBL_DEPARTMENT (FK_COUNTRY, NAME_ENG, NAME_RUS, NAME_I18N)
                    VALUES (131, NULL, 'dummy entry', NULL);


COMMIT WORK;

